name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "iot-backend/**"
      - '.github/workflows/docker-backend.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ github.run_id }}
      IMAGE_NAME: iot-backend
    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}

      - name: Do the deploy thing
        run: |
            ssh -o "StrictHostKeyChecking no" ${{ secrets.SSH_HOST }}@devrel-prodbox-nyc ""