name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "iot-backend/**"
      - '.github/workflows/docker-backend.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TIMESTAMP: ${{ github.run_id }}
      IMAGE_NAME: iot-backend
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      HOST: ${{ secrets.SSH_HOST }}
      NAME: ${{ secrets.SSH_NAME }}
      KEY: ${{ secrets.KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build ./$IMAGE_NAME --file ./${{env.IMAGE_NAME}}/Dockerfile --tag $IMAGE_NAME:$TIMESTAMP

      - name: Save Docker image to file
        run: docker save $IMAGE_TAG | gzip > iot-backend.tar.gz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: $TS_OAUTH_CLIENT_ID
          oauth-secret: $TS_OAUTH_SECRET
          tags: tag:whispern-ci

      - name: Execute SSH command on remote
        run: |
          cat > key.pem <<EOF
          ${SSH_KEY}
          EOF
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no nilsj@nilss-mac-mini.tailed622e.ts.net
          cd ~/Projects/iot-home/deployment/backend
          gunzip -f iot-backend.tar.gz
          docker load < iot-backend.tar
          docker stop iot-backend || true
          docker rm iot-backend || true
          docker run -d --name iot-backend -p 3000:3000 $IMAGE_NAME:$TIMESTAMP
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}