name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "iot-backend/**"
      - '.github/workflows/docker-backend.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TIMESTAMP: ${{ github.run_id }}
      IMAGE_NAME: iot-backend
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      HOST: ${{ secrets.SSH_NAME }}
    steps:
      - name: Build the Docker image
        run: docker build ./${{env.IMAGE_NAME}} --file ./${{env.IMAGE_NAME}}/Dockerfile --tag ${{env.IMAGE_NAME}}:${{ env.TIMESTAMP }}

      - name: Save Docker image to file
        run: docker save ${{ env.IMAGE_TAG }} | gzip > iot-backend.tar.gz
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: $TS_OAUTH_CLIENT_ID
          oauth-secret: $TS_OAUTH_SECRET
          tags: tag:whispern-ci

      - name: Do the deploy thing
        run: |
            ssh -o "StrictHostKeyChecking no" $HOST@nilss-mac-mini "
            cd ~/Projects/iot-home/deployment/backend
            gunzip -f iot-backend.tar.gz
            docker load < iot-backend.tar
            docker stop iot-backend || true
            docker rm iot-backend || true
            docker run -d --name iot-backend -p 3000:3000 ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }}
            "